blank_issues_enabled: true
contact_links:
  - name: 常见问题 FAQ
    url: ./blob/master/README.md#常见问题
    about: 先看看 README 里的常见问题，也许已经有答案了
  - name: 版本下载 Releases
    url: ./releases
    about: 下载最新版模块 / 查看更新记录
